// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type ModifRepo struct {
	Private bool   `json:"private"`
	Updater string `json:"updater"`
}

type NewRepo struct {
	Name    string `json:"name"`
	Private bool   `json:"private"`
	Owner   string `json:"owner"`
}

type NewUser struct {
	Name         string `json:"name"`
	Login        string `json:"login"`
	Email        string `json:"email"`
	AvatarURL    string `json:"avatarUrl"`
	Token        string `json:"token"`
	BlihUsername string `json:"blihUsername"`
	BlihToken    string `json:"blihToken"`
}

type Repo struct {
	Name      string `json:"name"`
	Private   bool   `json:"private"`
	GithubURL string `json:"githubURL"`
	Owner     string `json:"owner"`
	Updater   string `json:"updater"`
}

type User struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Login        string `json:"login"`
	Email        string `json:"email"`
	AvatarURL    string `json:"avatarURL"`
	Token        string `json:"token"`
	BlihUsername string `json:"blihUsername"`
	BlihToken    string `json:"blihToken"`
}
