// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewUser struct {
	Name      string `json:"name"`
	Login     string `json:"login"`
	Email     string `json:"email"`
	AvatarURL string `json:"avatarUrl"`
	Token     string `json:"token"`
}

type User struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Login     string `json:"login"`
	Email     string `json:"email"`
	AvatarURL string `json:"avatarURL"`
	Token     string `json:"token"`
}
