// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewUser struct {
	Name string `json:"name"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
